### ISSUE TITLE
Profile button alignment issue

### ISSUE THREAD

**Issue by Hedreon** [100photos/scultradark#14]
![firefox_AUBp4e1IRZ](https://github.com/JunkiEDM/scultradark/assets/39467046/1ae0b0e2-6ea4-4b6f-9c61-d22ef51bf299)

**Comment by Hedreon** [comment]
I just want this fixed

**Comment by Hedreon** [comment]
ok so I've found a temporary fix to this and it is by doing:
```css
.header__inner .header__right div.header__userNav .header__userNavUsernameButton {
	position: unset !important;
}
```
