### ISSUE TITLE
Border-color "glitch" on custom hue

### ISSUE THREAD

**Issue by davdi1337** [100photos/scultradark#5]
### When you change the hue value to anything else(my case the original soundcloud color is blue) the border-color a bit "glitchy" in the navbar and the tabs on library.
Not a big deal, but a bit annoying for me.

Here's the examples:
![Navbar border](https://i.imgur.com/FOukDE6.gif)
Also here too:
![Tabs border](https://i.imgur.com/rGhmC4c.gif)

**This code is fix the problem, if you mind to add it**
```css
.header__navWrapper .header__navMenu li a {
    filter: hue-rotate(/*[[hue]]*/deg) hue-rotate(-1deg) contrast(0.8) brightness(1.2) contrast(1.5) saturate(1.5) var(--fil)!important;
}
.sc-classic .g-tabs-link {
    filter: hue-rotate(/*[[hue]]*/deg) hue-rotate(-1deg) contrast(0.8) brightness(1.2) contrast(1.5) saturate(1.5) var(--fil)!important;
}
```
